server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: project-service
              uri: lb://project
              predicates:
                - Path=/api/projects/**,/api/tasks/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
