server:
  port: 8081
spring:
  application:
    name: project-service
  datasource:
    url: jdbc:postgresql://localhost:5432/workforge
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/