server:
  port: 8761
spring:
  application:
    name: discovery-server

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
